# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BoxMail' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoxMail
  pod 'XLPagerTabStrip', '~> 5.0'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
  pod 'Fakery', '~> 1.3'
end
